### ISSUE TITLE
How to close a disconnect client?

### ISSUE THREAD

**Issue by lexign** [ambelovsky/koa-socket-2#12]
How to close a disconnect client?
```js
io.on('disconnect', async (ctx) => {
  console.log('disconnect...', ctx.socket.id)
  ctx.socket.close() // or ctx.socket.client.close()
})
```

**Comment by ambelovsky** [comment]
Hi Chalin-Shi,

Please close the underlying socket connection by passing true to the disconnect function on the socket.

```js
io.on('disconnect', async (ctx) => {
  console.log('disconnect...', ctx.socket.id);
  ctx.socket.disconnect(true);
})
```

You can find the accompanying socket.io documentation here: https://socket.io/docs/server-api/#socket-disconnect-close
