### ISSUE TITLE
middleware [use] 

### ISSUE THREAD

**Issue by hackdie** [ambelovsky/koa-socket-2#14]
would be nice to have in the class `use` for the long polling. sometimes is good to auth the user before they actually connect. (connection got sockets is quite expensive, would be good to deny access before they actually connect.

right now im doing something like this. 

```app._io.use(async (socket, next) => {
  try {
    // const user = await axios.get('BASE_URL/user', {
    //   headers: { Authorization: socket.request.headers.authorization }
    // });
    socket.user = socket.request.headers.authorization;
    next();
  } catch (err) {
    console.log("someone without token", err.message);
    next(err);
  }
});
```

the `use` i found is a middleware for the `events` for socketio no for the `long polling`

**Comment by ambelovsky** [comment]
Hi hackdie,

You can access the underlying socket object directly.  Let me give you an example:

```
const Koa = require('koa');
const app = new Koa();

const IO = require('koa-socket-2');
const io = new IO();
io.attach(app);

io.socket.use(async (socket, next) => {
  try {
    let headers = socket.client.request.headers;
    if(!headers.authorization) throw new Error('No authorization header specified.');

    socket.user = socket.client.request.headers.authorization;
    next();
  } catch(err) {
    console.log(err.message);
    next(err);
    socket.disconnect();
  }
});

app.listen(8080);
```

**Comment by wenxiayili** [comment]
> Hi hackdie,
> 
> You can access the underlying socket object directly. Let me give you an example:
> 
> ```
> const Koa = require('koa');
> const app = new Koa();
> 
> const IO = require('koa-socket-2');
> const io = new IO();
> io.attach(app);
> 
> io.socket.use(async (socket, next) => {
>   try {
>     let headers = socket.client.request.headers;
>     if(!headers.authorization) throw new Error('No authorization header specified.');
> 
>     socket.user = socket.client.request.headers.authorization;
>     next();
>   } catch(err) {
>     console.log(err.message);
>     next(err);
>     socket.disconnect();
>   }
> });
> 
> app.listen(8080);
> ```

Why can't use 「**use**」 it?
