### ISSUE TITLE
how to join a room

### ISSUE THREAD

**Issue by yuu2lee4** [ambelovsky/koa-socket-2#2]
By wapped io instance? Or only can work on raw socket.io？

**Comment by ambelovsky** [comment]
That's correct.  This library wraps socket.io to better integrate with KOA, but it also provides some pass-through functionality for direct socket.io features like broadcast and compress.

**Comment by ambelovsky** [comment]
Reopening issue -- will take a look to make sure pass-through controls are available for joining and leaving rooms.

**Comment by ambelovsky** [comment]
Room management functionality should now be available.  Please let me know how well it works for you.  Thanks!

```js
io.on( 'some_event', ( ctx, data ) => {
  ctx.socket.join('some_room');
});

io.on( 'some_event', ( ctx, data ) => {
  ctx.socket.leave( 'some_room' );
});

io.to( 'some_room' ).emit( 'message', { hello: 'world' } );
```

**Comment by ambelovsky** [comment]
Note that you can also do the following to broadcast to all except the current user in a room:

```js
io.on( 'some_event', ( ctx, data ) => {
  ctx.socket.broadcast.to('some_room').emit('message', {hello: 'world'});
});
```

**Comment by ambelovsky** [comment]
Please note that io.to( 'some_room' ).emit( 'message', { hello: 'world' } ) had a bug that was fixed in the latest release.
