### ISSUE TITLE
How to resolve cors error!

### ISSUE THREAD

**Issue by xinyu-io** [ambelovsky/koa-socket-2#25]
I use @koa-cors

'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ambelovsky** [comment]
Please provide server code samples.

**Comment by xinyu-io** [comment]
```js
const IO = require("koa-socket-2")
  const io = new IO({
    ioOptions: {
      cors: {},
    },
  })
```
