### ISSUE TITLE
I want use 'PM2' to start my app. And i must use 'socket.io-redis'.

### ISSUE THREAD

**Issue by jasionLaw** [ambelovsky/koa-socket-2#3]
I do like :
`const IO = require( 'koa-socket-2' )`
`const sir = require( 'socket.io-redis' )`
`const io = new IO({`
  `adapter : sir({host : '127.0.0.1',port : 6380})`
`});
`
Did i used in wrong way?

**Comment by ambelovsky** [comment]
Hi jasionLaw!

Please "npm update" to get the latest version of koa-socket-2, and then try something like the following.

```js
const IO = require('koa-socket-2');
const Koa = require('koa');
const redis = require('socket.io-redis');

const app = new Koa();
const io = new IO();

io.attach(app);
io.adapter(redis({ host: 'localhost', port: 6379 }));
```

Please note that this is only required for cluster support in PM2.  You do not need this if you are not setting up a multi-node cluster.
